import type { User, Project, ProjectMembership, Application, Task, AnalyticsOverview } from '@/types';

export const SEED_USERS: User[] = [
  {
    id: 'user-alex',
    name: 'Alex Mercer',
    email: 'alex@college.edu',
    role: 'student',
    department: 'CSE',
    rollNumber: '23CS101',
    avatarUrl: '',
  },
  {
    id: 'user-sarah',
    name: 'Sarah Lin',
    email: 'sarah@college.edu',
    role: 'student',
    department: 'ECE',
    rollNumber: '23EC204',
    avatarUrl: '',
  },
  {
    id: 'user-karthik',
    name: 'Karthik Narang',
    email: 'karthik@college.edu',
    role: 'student',
    department: 'IT',
    rollNumber: '23IT312',
    avatarUrl: '',
  },
  {
    id: 'user-admin',
    name: 'Dr. Aris Thorne',
    email: 'admin@college.edu',
    role: 'admin',
    department: 'E-Cell Board',
    rollNumber: 'FAC-042',
    avatarUrl: '',
  },
];

export const SEED_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    code: 'CSE-882',
    title: 'Autonomous Micro-Drone Swarm',
    description: 'Decentralized mesh telemetry and obstacle mapping algorithms deployed across physical quadrotor nodes.',
    fullDescription: 'Students will construct an autonomous micro-quadrotor testbed capable of ad-hoc radio peer-to-peer localization, collaborative point cloud compression, and distributed geofencing under GPS-denied indoor environments.',
    departments: ['CSE', 'IT'],
    status: 'OPEN',
    deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    mentorName: 'Dr. Aris Vance',
    mentorRole: 'Autonomous Systems Lab',
    prerequisites: ['Proficiency in C++20 or Rust', 'ROS 2 or PX4 fundamentals', 'Linear Algebra & Kalman Filters'],
    guidelines: ['Hardware kits provided in Lab CSE-B4', 'Weekly sprint check-in on Mondays 5 PM', 'Code repository under PSGTech-ECell org'],
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'proj-2',
    code: 'ECE-612',
    title: 'EcoSense IoT Canopy',
    description: 'Low-latency environmental telemetry network utilizing LoRaWAN nodes for microclimate prediction.',
    fullDescription: 'Deployment of ultra-low power ambient sensing motes across campus buildings. Focuses on energy harvesting, edge inference for anomalous gas detection, and reliable MQTT broker integration.',
    departments: ['ECE', 'IT'],
    status: 'OPEN',
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    mentorName: 'Dr. Sarah Jenkins',
    mentorRole: 'Embedded Systems Research',
    prerequisites: ['Embedded C / FreeRTOS', 'Microcontroller peripherals (SPI/I2C/ADC)', 'Basic circuit layout review'],
    guidelines: ['Motes must run on <15uA sleep current', 'Field tests scheduled twice per semester'],
    createdAt: '2026-09-05T09:00:00Z',
  },
  {
    id: 'proj-3',
    code: 'CSE-404',
    title: 'CampusConnect Hub & Mobile Suite',
    description: 'Distributed microservices architecture and mobile client powering student venture collaboration.',
    fullDescription: 'The next evolution of student incubation services. Engineering scalable API gateways, automated grant disbursements, peer evaluation pipelines, and cross-platform native interfaces.',
    departments: ['CSE', 'ECE'],
    status: 'OPEN',
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    mentorName: 'Prof. Elena Rostova',
    mentorRole: 'Software Engineering Center',
    prerequisites: ['TypeScript & React / Next.js', 'PostgreSQL or MongoDB schema modeling', 'REST & GraphQL APIs'],
    guidelines: ['Strict test coverage >= 80%', 'Follow conventional commits'],
    createdAt: '2026-09-10T11:00:00Z',
  },
  {
    id: 'proj-4',
    code: 'MECH-330',
    title: 'Biometric Edge Telemetry OS',
    description: 'Ruggedized human-machine vibration telemetry system capturing structural fatigue in testing rigs.',
    fullDescription: 'High-speed sensor acquisition unit combining CAN-Bus interface with real-time vibration spectral analysis for engineering test benches.',
    departments: ['Mech', 'ECE'],
    status: 'DRAFT',
    deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    mentorName: 'Dr. Liam Thorne',
    mentorRole: 'Kinetic Dynamics Group',
    prerequisites: ['Digital Signal Processing', 'Vibration analysis', 'SolidWorks / MATLAB'],
    guidelines: ['Lab clearance required before operating test rigs'],
    createdAt: '2026-09-15T08:00:00Z',
  },
  {
    id: 'proj-5',
    code: 'CSE-202',
    title: 'QuantumSafe Crypt Layer',
    description: 'Post-quantum cryptographic key exchange integration for campus private network protocols.',
    fullDescription: 'Implementation of lattice-based encryption algorithms compliant with NIST standardization for internal authenticated microservices.',
    departments: ['CSE'],
    status: 'CLOSED',
    deadline: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // expired
    mentorName: 'Prof. A. Sridhar',
    mentorRole: 'Cybersecurity Lab',
    prerequisites: ['Abstract algebra & cryptography', 'C / Assembly'],
    guidelines: ['Strict security review required'],
    createdAt: '2026-08-01T10:00:00Z',
  },
];

export const SEED_MEMBERSHIPS: ProjectMembership[] = [
  // Project 1 (Autonomous Micro-Drone Swarm)
  {
    id: 'mem-1-alex',
    projectId: 'proj-1',
    userId: 'user-alex',
    role: 'REPRESENTATIVE', // Alex is Representative here
    joinedAt: '2026-09-02T10:00:00Z',
    user: SEED_USERS[0],
  },
  {
    id: 'mem-1-sarah',
    projectId: 'proj-1',
    userId: 'user-sarah',
    role: 'MEMBER', // Sarah is Member here
    joinedAt: '2026-09-03T11:00:00Z',
    user: SEED_USERS[1],
  },
  {
    id: 'mem-1-karthik',
    projectId: 'proj-1',
    userId: 'user-karthik',
    role: 'MEMBER',
    joinedAt: '2026-09-04T12:00:00Z',
    user: SEED_USERS[2],
  },

  // Project 2 (EcoSense IoT Canopy)
  {
    id: 'mem-2-karthik',
    projectId: 'proj-2',
    userId: 'user-karthik',
    role: 'REPRESENTATIVE',
    joinedAt: '2026-09-06T09:00:00Z',
    user: SEED_USERS[2],
  },
  {
    id: 'mem-2-alex',
    projectId: 'proj-2',
    userId: 'user-alex',
    role: 'MEMBER', // Alex is Member here!
    joinedAt: '2026-09-07T10:00:00Z',
    user: SEED_USERS[0],
  },

  // Project 3 (CampusConnect Hub & Mobile Suite)
  {
    id: 'mem-3-sarah',
    projectId: 'proj-3',
    userId: 'user-sarah',
    role: 'OWNER', // Sarah is OWNER here!
    joinedAt: '2026-09-11T10:00:00Z',
    user: SEED_USERS[1],
  },
  {
    id: 'mem-3-alex',
    projectId: 'proj-3',
    userId: 'user-alex',
    role: 'MEMBER',
    joinedAt: '2026-09-12T14:00:00Z',
    user: SEED_USERS[0],
  },
];

export const SEED_TASKS: Task[] = [
  // Project 1 Tasks
  {
    id: 'task-101',
    projectId: 'proj-1',
    title: 'Implement fail-safe geofencing protocol',
    description: 'Ensure drone initiates auto-landing sequence if RF packet loss exceeds 400ms.',
    status: 'To do',
    priority: 'High',
    assigneeId: 'user-alex',
    assigneeName: 'Alex Mercer',
    dueDate: '2026-10-06',
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'task-102',
    projectId: 'proj-1',
    title: 'Calibrate optical flow reflective markers',
    description: 'Mount retroreflective balls on alpha chassis and measure camera drift.',
    status: 'To do',
    priority: 'Medium',
    assigneeId: 'user-karthik',
    assigneeName: 'Karthik Narang',
    dueDate: '2026-10-08',
    createdAt: '2026-09-21T11:00:00Z',
    updatedAt: '2026-09-21T11:00:00Z',
  },
  {
    id: 'task-103',
    projectId: 'proj-1',
    title: 'SLAM point-cloud compression algorithm',
    description: 'Write octree pruning pipeline to stream 3D map data over 2.4GHz mesh.',
    status: 'In progress',
    priority: 'High',
    assigneeId: 'user-sarah',
    assigneeName: 'Sarah Lin',
    dueDate: '2026-10-10',
    createdAt: '2026-09-22T09:00:00Z',
    updatedAt: '2026-09-24T14:00:00Z',
  },
  {
    id: 'task-104',
    projectId: 'proj-1',
    title: 'MAVLink heartbeat serializer validation',
    description: 'Cross-check CRC checksum compliance against QGroundControl telemetry.',
    status: 'In progress',
    priority: 'Low',
    assigneeId: 'user-alex',
    assigneeName: 'Alex Mercer',
    dueDate: '2026-10-12',
    createdAt: '2026-09-23T15:00:00Z',
    updatedAt: '2026-09-25T11:00:00Z',
  },
  {
    id: 'task-105',
    projectId: 'proj-1',
    title: 'PX4 firmware CI/CD cross-compilation pipeline',
    description: 'Configured automated ARM GCC toolchain runner with unit tests.',
    status: 'Completed',
    priority: 'Medium',
    assigneeId: 'user-alex',
    assigneeName: 'Alex Mercer',
    dueDate: '2026-09-28',
    createdAt: '2026-09-18T10:00:00Z',
    updatedAt: '2026-09-28T16:00:00Z',
  },
  {
    id: 'task-106',
    projectId: 'proj-1',
    title: 'Dual LiDAR sensor bench mounting bracket',
    description: 'Drafted CAD model and 3D printed PETG test mount for alpha frame.',
    status: 'Completed',
    priority: 'Low',
    assigneeId: 'user-sarah',
    assigneeName: 'Sarah Lin',
    dueDate: '2026-09-27',
    createdAt: '2026-09-17T12:00:00Z',
    updatedAt: '2026-09-27T17:00:00Z',
  },

  // Project 2 Tasks
  {
    id: 'task-201',
    projectId: 'proj-2',
    title: 'LoRaWAN gateway channel plan configuration',
    description: 'Register EU868 frequencies with campus The Things Network server.',
    status: 'To do',
    priority: 'High',
    assigneeId: 'user-alex',
    assigneeName: 'Alex Mercer',
    dueDate: '2026-10-09',
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'task-202',
    projectId: 'proj-2',
    title: 'Power management deep sleep optimization',
    description: 'Verify RTC wake timer draws <12uA on Nordic nRF52 board.',
    status: 'In progress',
    priority: 'High',
    assigneeId: 'user-karthik',
    assigneeName: 'Karthik Narang',
    dueDate: '2026-10-14',
    createdAt: '2026-09-23T11:00:00Z',
    updatedAt: '2026-09-26T12:00:00Z',
  },
  {
    id: 'task-203',
    projectId: 'proj-2',
    title: 'Sensirion SHT40 temperature calibration',
    description: 'Benchmarked accuracy against standard laboratory reference thermometer.',
    status: 'Completed',
    priority: 'Medium',
    assigneeId: 'user-alex',
    assigneeName: 'Alex Mercer',
    dueDate: '2026-09-25',
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-25T16:00:00Z',
  },

  // Project 3 Tasks (CampusConnect Hub)
  {
    id: 'task-301',
    projectId: 'proj-3',
    title: 'Database connection pooling & failover',
    description: 'Tune Prisma client max pool connections under load spikes.',
    status: 'To do',
    priority: 'High',
    assigneeId: 'user-alex',
    assigneeName: 'Alex Mercer',
    dueDate: '2026-10-11',
    createdAt: '2026-09-24T10:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z',
  },
  {
    id: 'task-302',
    projectId: 'proj-3',
    title: 'Responsive navigation bar & mobile drawer',
    description: 'Ensure seamless tablet touch targets and smooth drawer collapse.',
    status: 'In progress',
    priority: 'Medium',
    assigneeId: 'user-sarah',
    assigneeName: 'Sarah Lin',
    dueDate: '2026-10-15',
    createdAt: '2026-09-25T14:00:00Z',
    updatedAt: '2026-09-27T10:00:00Z',
  },
  {
    id: 'task-303',
    projectId: 'proj-3',
    title: 'JWT authentication & refresh token rotation',
    description: 'Implemented secure HttpOnly cookie storage and expiry redirect flow.',
    status: 'Completed',
    priority: 'High',
    assigneeId: 'user-alex',
    assigneeName: 'Alex Mercer',
    dueDate: '2026-09-26',
    createdAt: '2026-09-16T11:00:00Z',
    updatedAt: '2026-09-26T17:00:00Z',
  },
  {
    id: 'task-304',
    projectId: 'proj-3',
    title: 'Role-based access middleware guards',
    description: 'Restricted administrative mutations on membership and applications.',
    status: 'Completed',
    priority: 'Medium',
    assigneeId: 'user-sarah',
    assigneeName: 'Sarah Lin',
    dueDate: '2026-09-28',
    createdAt: '2026-09-18T13:00:00Z',
    updatedAt: '2026-09-28T15:00:00Z',
  },
];

export const SEED_APPLICATIONS: Application[] = [
  {
    id: 'app-001',
    projectId: 'proj-1',
    studentId: 'user-karthik',
    studentName: 'Karthik Narang',
    studentEmail: 'karthik@college.edu',
    studentDepartment: 'IT',
    studentRollNumber: '23IT312',
    projectTitle: 'Autonomous Micro-Drone Swarm',
    projectCode: 'CSE-882',
    statement: 'Experienced with ROS2 humble nodes and C++ telemetry packets. Worked on robotics club quadcopter setup.',
    portfolioUrl: 'https://github.com/karthik-narang/ros2-telemetry',
    submittedDate: '2026-09-18T10:30:00Z',
    status: 'Under Review',
  },
  {
    id: 'app-002',
    projectId: 'proj-2',
    studentId: 'user-alex',
    studentName: 'Alex Mercer',
    studentEmail: 'alex@college.edu',
    studentDepartment: 'CSE',
    studentRollNumber: '23CS101',
    projectTitle: 'EcoSense IoT Canopy',
    projectCode: 'ECE-612',
    statement: 'Interested in low-power firmware and MQTT ingestion architectures.',
    portfolioUrl: 'https://github.com/alex-mercer/firmware-tools',
    submittedDate: '2026-09-15T14:20:00Z',
    status: 'Accepted',
    reviewedAt: '2026-09-17T09:00:00Z',
    reviewedBy: 'Dr. Aris Thorne',
  },
  {
    id: 'app-003',
    projectId: 'proj-5',
    studentId: 'user-alex',
    studentName: 'Alex Mercer',
    studentEmail: 'alex@college.edu',
    studentDepartment: 'CSE',
    studentRollNumber: '23CS101',
    projectTitle: 'QuantumSafe Crypt Layer',
    projectCode: 'CSE-202',
    statement: 'Studied Kyber and Dilithium implementations in graduate reading course.',
    portfolioUrl: 'https://github.com/alex-mercer/pqc-benchmarks',
    submittedDate: '2026-08-10T16:00:00Z',
    status: 'Rejected',
    reviewedAt: '2026-08-15T11:00:00Z',
    reviewedBy: 'Dr. Aris Thorne',
  },
  {
    id: 'app-004',
    projectId: 'proj-3',
    studentId: 'user-alex',
    studentName: 'Alex Mercer',
    studentEmail: 'alex@college.edu',
    studentDepartment: 'CSE',
    studentRollNumber: '23CS101',
    projectTitle: 'CampusConnect Hub & Mobile Suite',
    projectCode: 'CSE-404',
    statement: 'Lead full-stack developer with 2 years of React, Next.js, and Node experience.',
    portfolioUrl: 'https://github.com/alex-mercer/fullstack-showcase',
    submittedDate: '2026-09-12T11:00:00Z',
    status: 'Accepted',
    reviewedAt: '2026-09-13T10:00:00Z',
    reviewedBy: 'Dr. Aris Thorne',
  },
  {
    id: 'app-005',
    projectId: 'proj-2',
    studentId: 'user-sarah',
    studentName: 'Sarah Lin',
    studentEmail: 'sarah@college.edu',
    studentDepartment: 'ECE',
    studentRollNumber: '23EC204',
    projectTitle: 'EcoSense IoT Canopy',
    projectCode: 'ECE-612',
    statement: 'Passionate about environmental sensor calibration and hardware design.',
    portfolioUrl: 'https://github.com/sarah-lin/iot-sensors',
    submittedDate: '2026-09-24T15:45:00Z',
    status: 'Under Review',
  },
];

export const SEED_ANALYTICS: AnalyticsOverview = {
  activeProjects: 3,
  totalApplicants: 28,
  overallCompletionRate: 64,
  activeDepartments: 4,
  departmentDistribution: [
    { department: 'CSE', count: 3, percentage: 50 },
    { department: 'IT', count: 2, percentage: 33 },
    { department: 'ECE', count: 2, percentage: 33 },
    { department: 'Mech', count: 1, percentage: 17 },
  ],
  nearingDeadlineProjects: [
    {
      id: 'proj-1',
      code: 'CSE-882',
      title: 'Autonomous Micro-Drone Swarm',
      deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
      daysRemaining: 12,
      departments: ['CSE', 'IT'],
    },
    {
      id: 'proj-2',
      code: 'ECE-612',
      title: 'EcoSense IoT Canopy',
      deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
      daysRemaining: 18,
      departments: ['ECE', 'IT'],
    },
  ],
};
